---
title: "dada2_titan_euc"
author: "samuel beauregard"
date: "2023-07-05"
output: html_document
---

# Setting up 
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/seq/seq_euc")
```

```{r}
library(dada2)

path <- "~/seqs/seq_euc"
list.files(path) #shows files in the folder set by the path 

fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE)) 
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))

names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
plotQualityProfile(fnFs, aggregate=TRUE) #vérifier qualité reads, trimmer trunclen à la longueur requise pour chaque échantillon.
plotQualityProfile(fnRs, aggregate=TRUE) #vérifier qualité reads, trimmer trunclen à la longueur requise pour chaque échantillon.
```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft = c(21,20), truncLen=c(250,200), #si nbr séquences drop trop vite, vérifier si trunlen est approprié, peut rallonger au besoin , trimleft: a changer pour euc
                     maxN=0, maxEE=2, truncQ=2,rm.phix=TRUE, 
                     compress=TRUE) #multithread = T removed #maxEE=nbr erreurs, peut mettre à 4 pour que ce soit plus permissif, googler les autres paramètres au besoin

errF <- learnErrors(filtFs, randomize=TRUE) #multithread = T removed
errR <- learnErrors(filtRs, randomize=TRUE) #multithread = T removed

# visualize the estimated error rates:
# plotErrors(errF, nominalQ=TRUE)

# Apply the core sample inference algorithm to the filtered and trimmed sequence data
dadaFs <- dada(filtFs, err=errF, pool = "pseudo") #multithread = T removed
dadaRs <- dada(filtRs, err=errR, pool = "pseudo") #multithread = T removed

# Merge paired reads
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs)
```

```{r}
# Construct an amplicon sequence variant table (ASV) table (a higher-resolution version of the OTU table produced by traditional methods)
seqtab <- makeSequenceTable(mergers)
#View dimension of your matrices 
dim(seqtab)
# Inspect distribution of sequence lengths
table(nchar(getSequences(seqtab))) # pour bac, devrait être approx 444 paires bases
# Remove chimeras 
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus") #multithread = T removed
#View dimension of your matrices 
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)

# Track reads through the pipeline (obtain the count of how many sequences were deleted at each steps) 
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
track

# ----------------- ID TAXA Classification ----------------- 

# Classify using DADA2 function assignTaxonomy


# Install pr2database in R (if needed):
install.packages('pr2database', repos = c('https://pr2database.r-universe.dev', 'https://cloud.r-project.org'))

#download the database to the server (one time) from this website: https://app.pr2-database.org/pr2-database/

taxa = assignTaxonomy(seqtab.nochim, "~/script/DADA2/pr2_version_5.0.0_SSU_dada2.fasta.gz", tryRC=TRUE, taxLevels = c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species")) #multithread = T removed
#aller chercher bases de données, pas les mêmes pour bac et euc
```

```{r}
write.csv(taxa, file = "~/DADA2_output/euc/classified_taxa_euc.csv") #

# Add the higher identified taxonomic rank to unclassified ranks and remove non-eukaryote Kingdoms.  
taxid=data.frame(t(taxa))
taxid[] <- lapply(taxid, as.character)
taxa2<- tidyr::fill(taxid, colnames(taxid),.direction = "down")
taxa2<- sapply(taxa2, function(x){paste0("Unclassified_", x)})
taxid[is.na(taxid)] <- taxa2[is.na(taxid)]
taxid <- t(taxid)
# Remove ASV not classified as eukaryote from the tax table then from the ASV matrix 
taxid=subset(as.data.frame(taxid), !Kingdom =="Bacteria") #remplacer par eucaryotes pour l'autre script
#Est-ce que je devrais l'activer? seqtab.nochim <- seqtab.nochim[,colnames(seqtab.nochim) %in% rownames(taxid)]
# Save sequence table 
write.csv(seqtab.nochim, file = "~/DADA2_output/euc/seqtab_nonchim_euc.csv")

```

```{r}
# ----------------- Decontam ----------------- 
library(decontam)
library(phyloseq)

meta <- read.table("~/meta.csv", sep=";", row.names=1, header=TRUE)
ps <- phyloseq(otu_table(t(seqtab.nochim), taxa_are_rows=TRUE), tax_table(as.matrix(taxid)), sample_data(meta))
sample_data(ps)$is.neg <- sample_data(ps)$is.neg == "TRUE" #modifier en fonction du fichier de metadata que je fais

contamdf.prev <- isContaminant(ps, method="prevalence", neg="is.neg", threshold=0.5)
table(contamdf.prev$contaminant)
ps.noncontam <- prune_taxa(!contamdf.prev$contaminant, ps)
ps_decontam=subset_samples(ps.noncontam, !is.neg=="TRUE")
``` 

# Phylogenetic Tree  
Extract sequences from phyloseq object `ps_decontam` and align them using `AlignSeqs` function from `DECIPHER` 
```{r}
library(dada2)
library(DECIPHER)
asv_tab=as.data.frame(otu_table(ps_decontam))
seqs <- getSequences(t(asv_tab))
names(seqs) <- seqs
seq_align <- AlignSeqs(DNAStringSet(seqs), anchor=NA, processors=20)
path="~/combined_fastq/euc"
writeXStringSet(seq_align, file = file.path(path,"align.fasta_euc"),format="fasta")
``` 
Create tree using FastTree. FastTree is not an R library but rather a linux program and therefor these commands are written in `bash` 
```{bash}
cd ~/combined_fastq/euc
fasttree -nt -gtr  align.fasta_euc > align_tree_euc
``` 

Add midpoint rooting to tree  
```{r}
library(dada2)
Tree <- ape::read.tree(file = file.path(path,"align_tree_euc"))
Tree.midpoint <- phangorn::midpoint(Tree)
ape::write.tree(Tree.midpoint,file = file.path(path,"tree.midpoint_euc"))
``` 
Add tree to phyloseq object 
```{r}
library(phyloseq)
tree <- phy_tree(Tree.midpoint)
ps1 <- merge_phyloseq(ps_decontam, tree)
# Make ASV ID shorter 
taxa_names(ps1) <- paste0("ASV", seq(ntaxa(ps1)))
``` 

Save the tables 
```{r}
write.csv(as.data.frame(as(tax_table(ps1), "matrix")), file = "~/DADA2_output/euc/raw_taxa_euc.csv")
write.csv(as.data.frame(as(otu_table(ps1), "matrix")),file = "~/DADA2_output/euc/raw_asv_euc.csv")
write.csv(as.data.frame(as(sample_data(ps1), "matrix")), file="~/DADA2_output/euc/raw_meta_euc.csv")
tree.raw <- phy_tree(ps1)
ape::write.tree(tree.raw , file = "~/DADA2_output/euc/raw_tree_euc.tree")
```

