---
title: "GAM_euc"
output: html_document
date: "2024-04-05"
---

#install required packages (only do once)
```{r}
# install.packages("mgcv")
# install.packages('phyloseq')
# install.packages('vegan')
# install.packages('ggplot2')
# install.packages('scales')
# install.packages('gratia')
#install.packages('MuMIn')
#install.packages('DHARMa')
```

```{r}
library(phyloseq)
library(vegan)
library(ggplot2)
library(scales)
library(tidyr)
library(mgcv)
library(gratia)
library(MuMIn)
library(mvgam)
```

#load data
```{r}
asv=read.table( "~/stats/median_asv_GAM_euc.csv", sep=",", row.names=1, header=TRUE, check.names=FALSE)
meta=read.table("~/stats/median_meta_GAM_euc.csv", sep=",", row.names=1, header=TRUE)
taxa=read.table("~/stats/median_taxa_GAM_euc.csv", sep=",", row.names=1, header=TRUE)

```


#Shannon index through time
```{r}

#create phyloseq object
ps=phyloseq(otu_table(asv, taxa_are_rows=TRUE), tax_table(as.matrix(taxa)), sample_data(meta))

#get shannon index
shannon = cbind(estimate_richness(ps,measures = 'shannon'),
            sample_data(ps))


#assign factor instread of chr
shannon$experience <- as.factor(shannon$experience)
shannon$bioreactor <- as.factor(shannon$bioreactor)
shannon$Sample_type <- as.factor(shannon$Sample_type)

#select only the first experiment
shannon1 <- shannon[shannon$experience == 'E1',]
#select rocks from first experiment
shannon1R <- shannon1[shannon1$short_sample_type == 'R',]

#select only the second experiment
shannon2 <- shannon[shannon$experience == 'E2',]

shannon2W <- shannon2[shannon2$short_sample_type == 'W',]

#renumber time so it goes from 1-24 instead of 22-45
shannon2W$time <- shannon2W$time-21
```

#visualize data (verify homoscedasticity)
```{r}
hist(shannon1R$Shannon)
summary(shannon1R$Shannon)

hist(shannon2W$Shannon)
summary(shannon2W$Shannon)
```


run model for sessile succession
```{r}
model1R_G_te <- gam(Shannon ~ te(dic, doc, bs = 'tp')  + s(time) + s(time, by = bioreactor, bs = 'tp', m = 1) + s(bioreactor, bs = "re"),  
method = 'REML', family = Gamma(link = identity),  gamma = 1, select = TRUE, data = shannon1R)                     
              
```


```{r}
gam.check(model1R_G_te, rep = 1000)

summary(model1R_G_te)

summ <- draw(model1R_G_te, residuals = F, wrap = F, rug = F)
gen_trend_gam <- summ[[2]] +  
  theme_classic() +
    geom_line(size = 1.5)+
  theme(
    panel.grid = element_blank(),
    text = element_text(size = 24),)+
  xlab('Time (days)')

gen_trend_gam

 #save gen trend
ggsave(filename = "euc_gen_trend_GAM_E1_sessile.pdf", plot = gen_trend_gam, path = "~/stats/GAM/euc/", device = "pdf")
```

```{r}
vis.gam(model1R_G_te, theta = 160, ticktype="detailed", type = 'response')

p <- plot_predictions(model1R_G_te, condition = c('time', 'bioreactor'), type = 'response',  points = 1, rug = F) #to get the shared+group trends

# Modify the lines within the ggplot object
p$layers <- lapply(p$layers, function(layer) {
  if ("GeomLine" %in% class(layer$geom)) {  # Check if it's a line layer
    layer$aes_params$size <- 2  # Increase line thickness
  }
  return(layer)
})

# Adjust the y-axis limits using ggplot2
gen <- p  + ylim(0.95, 5)  + 
  theme_classic() +
  ylab('Alpha diversity (H)')+
   xlab("Time (days)") +
  theme(
   panel.grid = element_blank(),
    text = element_text(size = 24),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = "black") # Set axis text color to black
  ) +
  scale_color_viridis_d(option = "D")

gen

  #save
ggsave(filename = "euc_GAM_E1_sessile.pdf", plot = gen, path = "~/stats/GAM/euc/", device = "pdf", width = 10, height = 7.5)  
```

```{r}
plot_predictions(model1R_G_te, condition = c('doc', 'dic'), type = 'response', points = 1, rug = TRUE)

plot_predictions(model1R_G_te, condition = c('dic', 'doc'), type = 'response',   points = 1, rug = TRUE)
```

```{r}
vis.gam(model1R_G_te, type = 'response', ticktype = 'detailed', theta = 180)

vis.gam(model1R_G_te, type = 'response', ticktype = 'detailed', theta = 270, se = 1)
```



create model for planctonic community exp. 2 (recolonization of sterile water)
  doc is removed as it is too highly correlated with time
```{r}
hist(shannon2W$Shannon)
```

```{r}
shannon2W <- shannon2W %>% dplyr::select(c(dic, time, bioreactor, Shannon))


model2W_G_te <- gam(Shannon ~ te(dic, bs = 'tp', k = 10) + s(time, k = 15) + s(time, by = bioreactor, bs = 'tp', k = 10, m = 1) + s(bioreactor, bs = "re"),
method = 'REML', family = Gamma(link = identity),  gamma = 1, select = TRUE, data = shannon2W)                                     
```

```{r}
gam.check(model2W_G_te, rep = 1000)

summary(model2W_G_te)

summ <- draw(model2W_G_te, residuals = F, wrap = F, rug =F)
gen_trend_gam <- summ[[2]] +  
  theme_classic() +
    geom_line(size = 1.5)+
  theme(
    panel.grid = element_blank(),
    text = element_text(size = 24))+
  xlab('Time (days)')

gen_trend_gam

 #save gen trend
ggsave(filename = "euc_gen_trend_GAM_E2_plankto.pdf", plot = gen_trend_gam, path = "~/stats/GAM/euc/", device = "pdf")  
```

```{r}
p <- plot_predictions(model2W_G_te, condition = c('time', 'bioreactor'), type = 'response',  points = 1, rug = F)

# Modify the lines within the ggplot object
p$layers <- lapply(p$layers, function(layer) {
  if ("GeomLine" %in% class(layer$geom)) {  # Check if it's a line layer
    layer$aes_params$size <- 2  # Increase line thickness
  }
  return(layer)
})

# Adjust the y-axis limits using ggplot2
gen <- p  + ylim(0.95, 5)  + 
  theme_classic() +
  ylab('Alpha diversity (H)')+
   xlab("Time (days)") +
  theme(
   panel.grid = element_blank(),
    text = element_text(size = 24),
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5),
    axis.text = element_text(color = "black") # Set axis text color to black
  ) +
  scale_color_viridis_d(option = "D")

gen

  #save
ggsave(filename = "euc_GAM_E2_plankto.pdf", plot = gen, path = "~/stats/GAM/euc/", device = "pdf", width = 10, height = 7.5)  
```


```{r}
plot_predictions(model2W_G_te, condition = c('dic', 'bioreactor'), type = 'response',  points = 1, rug = TRUE)
```
